### ISSUE TITLE
gfootgen does not start: "Gtk::ListStore#set_column_types: wrong number of arguments"

### ISSUE THREAD

**Issue by Shadyman** [ehennes775/gfootgen#21]
Followed installation instructions provided, installed all packages listed in the readme.md, uncommented the gfootgen.gemspec lines, built and installed the gem, and get this when trying to run:

> $ gfootgen
> Traceback (most recent call last):
> 
>         16: from /usr/local/bin/gfootgen:23:in `<main>'
>         15: from /usr/local/bin/gfootgen:23:in `load'
>         14: from /var/lib/gems/2.5.0/gems/gfootgen-0.0.1/bin/gfootgen:20:in `<top (required)>'
>         13: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
>         12: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
>         11: from /var/lib/gems/2.5.0/gems/gfootgen-0.0.1/lib/gfootgen.rb:26:in `<top (required)>'
>         10: from /var/lib/gems/2.5.0/gems/gfootgen-0.0.1/lib/gfootgen.rb:26:in `require_relative'
>          9: from /var/lib/gems/2.5.0/gems/gfootgen-0.0.1/lib/gfootgen/gui.rb:24:in `<top (required)>'
>          8: from /var/lib/gems/2.5.0/gems/gfootgen-0.0.1/lib/gfootgen/gui.rb:24:in `require_relative'
>          7: from /var/lib/gems/2.5.0/gems/gfootgen-0.0.1/lib/gfootgen/gui/outline_widget.rb:19:in `<top (required)>'
>          6: from /var/lib/gems/2.5.0/gems/gfootgen-0.0.1/lib/gfootgen/gui/outline_widget.rb:24:in `<module:Gui>'
>          5: from /var/lib/gems/2.5.0/gems/gfootgen-0.0.1/lib/gfootgen/gui/outline_widget.rb:29:in `<class:OutlineWidget>'
>          4: from /var/lib/gems/2.5.0/gems/gfootgen-0.0.1/lib/gfootgen/gui/outline_widget.rb:29:in `new'
>          3: from /var/lib/gems/2.5.0/gems/gfootgen-0.0.1/lib/gfootgen/gui/outline_catalog.rb:47:in `initialize'
>          2: from /usr/lib/ruby/vendor_ruby/gobject-introspection/loader.rb:574:in `block in define_method'
>          1: from /usr/lib/ruby/vendor_ruby/gobject-introspection/loader.rb:661:in `build'
> 
> /usr/lib/ruby/vendor_ruby/gobject-introspection/loader.rb:712:in `validate_arguments': Gtk::ListStore#set_column_types: wrong number of arguments (2 for 1) (ArgumentError)

ruby --version returns _ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]_
OS is Kubuntu 18.04

**Comment by Shadyman** [comment]
As an addendum, I had gfootgen working perfectly on 14.04 (and loved it!) so something must have changed in ruby since then

**Comment by ehennes775** [comment]
**Works Under**
Ubuntu 16.04 LTS
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
ruby-gtk 2.2.5-4build1

**GIR File Snippet in Ubuntu 16.04 LTS**
```xml
<method name="set_column_types"
        c:identifier="gtk_list_store_set_column_types">
  <doc xml:space="preserve">This function is meant primarily for #GObjects that inherit from #GtkListStore,
and should only be used when constructing a new #GtkListStore.  It will not
function after a row has been added, or a method on the #GtkTreeModel
interface is called.</doc>
  <return-value transfer-ownership="none">
    <type name="none" c:type="void"/>
  </return-value>
  <parameters>
    <instance-parameter name="list_store" transfer-ownership="none">
      <doc xml:space="preserve">A #GtkListStore</doc>
      <type name="ListStore" c:type="GtkListStore*"/>
    </instance-parameter>
    <parameter name="n_columns" transfer-ownership="none">
      <doc xml:space="preserve">Number of columns for the list store</doc>
      <type name="gint" c:type="gint"/>
    </parameter>
    <parameter name="types" transfer-ownership="none">
      <doc xml:space="preserve">An array length n of #GTypes</doc>
      <array length="0" zero-terminated="0" c:type="GType*">
        <type name="GType" c:type="GType"/>
      </array>
    </parameter>
  </parameters>
</method>
```

**Comment by ehennes775** [comment]
**Not Working Under**
Ubuntu 18.04.1 LTS
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
ruby-gtk3 3.2.4-1

**GIR File Snippet in Ubuntu 18.04.1 LTS**
```xml
<method name="set_column_types"
        c:identifier="gtk_list_store_set_column_types">
  <doc xml:space="preserve">This function is meant primarily for #GObjects that inherit from #GtkListStore,
and should only be used when constructing a new #GtkListStore.  It will not
function after a row has been added, or a method on the #GtkTreeModel
interface is called.</doc>
  <return-value transfer-ownership="none">
    <type name="none" c:type="void"/>
  </return-value>
  <parameters>
    <instance-parameter name="list_store" transfer-ownership="none">
      <doc xml:space="preserve">A #GtkListStore</doc>
      <type name="ListStore" c:type="GtkListStore*"/>
    </instance-parameter>
    <parameter name="n_columns" transfer-ownership="none">
      <doc xml:space="preserve">Number of columns for the list store</doc>
      <type name="gint" c:type="gint"/>
    </parameter>
    <parameter name="types" transfer-ownership="none">
      <doc xml:space="preserve">An array length n of #GTypes</doc>
      <array length="0" zero-terminated="0" c:type="GType*">
        <type name="GType" c:type="GType"/>
      </array>
    </parameter>
  </parameters>
</method>
```

**Comment by ehennes775** [comment]
I believe the program should work again after the latest updates.
